const Combined = @import("combined.zig").Combined;
pub const Latin2 = enum(u8) {
    A_with_ogonek = 161,
    breve = 162,
    L_with_stroke = 163,
    L_with_caron = 165,
    S_with_acute_accent = 166,
    S_with_caron = 169,
    S_with_cedilla = 170,
    T_with_caron = 171,
    Z_with_acute_accent = 172,
    Z_with_caron = 174,
    Z_with_dot_above = 175,
    a_with_ogonek = 177,
    ogonek = 178,
    l_with_stroke = 179,
    l_with_caron = 181,
    s_with_acute_accent = 182,
    caron = 183,
    s_with_caron = 185,
    s_with_cedilla = 186,
    t_with_caron = 187,
    z_with_acute_accent = 188,
    double_acute_accent = 189,
    z_with_caron = 190,
    z_with_dot_above = 191,
    R_with_acute_accent = 192,
    A_with_breve = 195,
    L_with_acute_accent = 197,
    C_with_acute_accent = 198,
    C_with_caron = 200,
    E_with_ogonek = 202,
    E_with_caron = 204,
    D_with_caron = 207,
    D_with_stroke = 208,
    N_with_acute_accent = 209,
    N_with_caron = 210,
    O_with_double_acute_accent = 213,
    R_with_caron = 216,
    U_with_ring_above = 217,
    U_with_double_acute_accent = 219,
    T_with_cedilla = 222,
    r_with_acute_accent = 224,
    a_with_breve = 227,
    l_with_acute_accent = 229,
    c_with_acute_accent = 230,
    c_with_caron = 232,
    e_with_ogonek = 234,
    e_with_caron = 236,
    d_with_caron = 239,
    d_with_stroke = 240,
    n_with_acute_accent = 241,
    n_with_caron = 242,
    o_with_double_acute_accent = 245,
    r_with_caron = 248,
    u_with_ring_above = 249,
    u_with_double_acute_accent = 251,
    t_with_cedilla = 254,
    dot_above = 255,

    pub fn toCombined(self: Latin2) Combined {
        return @intToEnum(Combined, (@as(u16, 1) << 8) | @enumToInt(self));
    }
    pub fn next(self: Latin2) Latin2 {
        return @intToEnum(Latin2, @enumToInt(self) + 1);
    }
};
