#!/usr/bin/env sh
set -ex

rm -f zig-out/fontnames.txt
zig build getserverfontnames > zig-out/fontnames.txt
font=$(head -n 1 zig-out/fontnames.txt)

zig build queryfont -- $font > /dev/null

zig build example
zig build fontviewer
zig build input
zig build graphics
zig build testexample

echo Success
